# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeGallParse', '0002_auto_20170705_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='postNum',
        ),
        migrations.AlterField(
            model_name='postdata',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
